server:
  port: 8081
error:
  include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kitchenstorage
    username: root
    password: root
  security:
    user:
      name: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

logging:
  level:
    org.springframework.security: DEBUG

aws:
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}REGION