package com.example.kitchenStorage.lovet;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Data
@Entity
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBDocument
@DynamoDBTable(tableName = "kitchenstorage")
@Table(name = "items")
public class ksEntity {

    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @DynamoDBAttribute
    @Column(name = "name", unique = true)
    private String name;

    @DynamoDBAttribute
    @JsonProperty("category_name")
    @Column(name = "category_name")
    private String categoryName;

    @DynamoDBAttribute
    @Column(name = "quantity")
    private Integer quantity;

    @DynamoDBAttribute
    @JsonProperty("stored_in")
    @Column(name = "stored_in")
    private String storedIn;

    @DynamoDBAttribute
    @JsonProperty("expiration_date")
    @Column(name = "expiration_date")
    private LocalDate expirationDate;
}
