name: Build and Deploy to EC2

on:
  push:
    branches:
      - master   # Trigger on push to the master branch
  pull_request:
    branches:
      - master   # Trigger on pull request to the master branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adoptium'
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true

      - name: Build project with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t lovetcs/ks-app:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push lovetcs/ks-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Only run after the build job is successful
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy SSH key
        run: echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Set SSH permissions
        run: chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known hosts
        run: |
          ssh-keyscan -H 3.10.178.134  >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.10.178.134  << 'EOF'
            docker pull lovetcs/ks-app:latest
            docker stop ks-app || true
            docker rm ks-app || true
            docker run -d -p 8081:8081 --name ks-app lovetcs/ks-app:latest
          EOF
