name: Build and Deploy to EC2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project with Maven
        run: |
          cd lovet
          mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          cd lovet/src/main/java/com/example/kitchenStorage/lovet
          docker build -t lovetcs/ks-app:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push lovetcs/ks-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 3.10.178.134 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.10.178.134 << 'EOF'
            docker pull lovetcs/ks-app:latest
            docker stop ks-app || true
            docker rm ks-app || true
            docker run -d -p 8081:8081 --name ks-app lovetcs/ks-app:latest
          EOF